name: Deploy to VPS

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: 22
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            if [ ! -d "/var/www/tests/back/.git" ]; then
                cd /var/www/tests/back
                git init
                git remote add origin https://github.com/Tektech-fr/test-deploy-back.git
                git pull origin production
                npm install
                pm2 start server.js --name "SERVER"
            else
                cd /var/www/tests/back
                git pull
                npm install
                pm2 restart SERVER
            fi
