name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files
        run: |
          echo "Listing files in current directory:"
          ls -l
          echo "::set-output name=files::$(ls)"
        id: list_files
