on:
  push:
    branches:
      - production

jobs:
  Preparer_les_fichiers:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v4

      - name: Copier les fichiers vers le VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          key: ${{ secrets.VPS_KEY }}
          source: "."
          target: ${{ secrets.VPS_TARGET_PATH }}
