name: Deploy to server

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files
        run: |
          echo "Listing files in current directory:"
          ls -l
          echo "::set-output name=files::$(ls)"
        id: list_files

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          key: ${{ secrets.VPS_KEY }}
          source: ${{ steps.list_files.outputs.files }}
          target: /tmp/back-express
