on:
  push:
    branches:
      - production

jobs:
  Preparer_les_fichiers:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v4

      - name: Lancer le script sur le VPS
        env:
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_TARGET_PATH: ${{ secrets.VPS_TARGET_PATH }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          rsync -av --exclude='.git' --exclude='.github' --exclude='.gitignore' ./ $VPS_USERNAME@$VPS_HOST:$VPS_TARGET_PATH
