on:
  push:
    branches: production

jobs:
  Preparer_les_fichiers:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.14.0"

      - name: Installer les dépendances
        run: npm ci

      - name: Lancer le script sur le VPS
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.VPS_USERNAME }}
          host: ${{ secrets.VPS_HOST }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd tmp/test-copy
            echo "Salut" > test.txt
